#!/bin/sh

if [ -z "$1" ]
then
    echo "Usage: $0 program"
    exit 1
fi

PROG=$(readlink -f $1)
PROG_ID=$(basename ${PROG%.*})

cd $(dirname $0)

for IN_FILE in $PROG_ID/*.in
do
    TEST_ID=${IN_FILE%.*}
    OUT_FILE=$TEST_ID.out
    PROG_OUT=$($PROG < $IN_FILE)
    EXPECT_OUT=$(cat $OUT_FILE)
    echo ==== $TEST_ID ====
    if [ "$PROG_OUT" != "$EXPECT_OUT" ]; then
        echo ---- Program Output ----
        echo $PROG_OUT
        echo ------------------------
        echo ---- Expected Output ---
        echo $EXPECT_OUT
        echo ------------------------
        exit 1
    fi
done
